# Autogenerated wrapper script for ZPares_jll for x86_64-w64-mingw32-libgfortran4
export libzpares

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("ZPares")
JLLWrappers.@declare_library_product(libzpares, "libzpares.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libzpares,
        "bin\\libzpares.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
